public with sharing class SimpleSOQL1 
{
    public Contact getContact(Id contId)
    {
        // change this method to return the contact
        // record for the supplied id - include the
        // contac'ts first and last name in the 
        // results

        return null;
    }

    public List<Contact> getCEOs()
    {
        // change this method to return all contacts with the 
        // title of 'CEO'. Include the First name, last name and 
        // title fields in the returned results

        return null;
    }

    public Contact getYoungest()
    {
        // change this method to return the youngest contact
        // in the org. Include their date of birth in the 
        // return result

        return null;
    }

    public List<Contact> getContactsForAccounts(List<Account> accounts)
    {
        // change this method to return all contacts for the supplied
        // accounts

        return null;
    }

    public Contact getFieldsForContact(Id contId, String field1, String field2)
    {
        // change this method to return the contact record for the supplied id. Include
        // the fields named in the parameters 'field1' and 'field2' in the results. E.g.
        // if field1 is 'FirstName' then the returned record must contain the contact's
        // first name

        return null;
    }
}
